export const CATEGORIES = [
  {
    slug: "single-phase",
    label: "Single Phase Hybrid & Off-Grid",
    icon: "Zap",
    desc: "1.5kW to 12.6kW hybrid & off-grid inverters for homes and SMEs in Bangladesh.",
  },
  {
    slug: "three-phase-hybrid",
    label: "Three Phase Hybrid (LV & HV)",
    icon: "Grid",
    desc: "5kW to 30kW three-phase hybrid with parallel, GEN port & IP66.",
  },
  {
    slug: "on-grid",
    label: "On-Grid Inverters",
    icon: "Plug",
    desc: "Volmore 1kW to 350kW high-efficiency on-grid for net-metering & industrial.",
  },
  {
    slug: "solar-pump",
    label: "Solar Pump Controllers",
    icon: "Droplets",
    desc: "2.2kW to 200kW solar water pumping for agriculture & irrigation.",
  },
  {
    slug: "ess",
    label: "All-in-One ESS & Batteries",
    icon: "Battery",
    desc: "NURA ESS + LiFePO4 wall, mobile & HV stacks up to 900kWh.",
  },
  {
    slug: "complete-solutions",
    label: "Complete Solar Solutions",
    icon: "Sun",
    desc: "System design, supply, installation support & consultation.",
  },
];
const U = (id, w = 1200) =>
  `https://images.unsplash.com/${id}?q=80&w=${w}&auto=format&fit=crop`;
export const IMG = {
  hero: U("photo-1509391366360-2e959784a276", 1920),
  roof: U("photo-1508514177221-188b1cf16e9d"),
  field: U("photo-1466611653911-95081537e5b7"),
  home: U("photo-1613665813446-82a78c468a1d"),
  battery: U("photo-1593941707882-a5bba14938c7"),
  agri: U("photo-1521618755572-156ae0cdd74d"),
  ind: U("photo-1497440001374-f26997328c1b"),
  panel: U("photo-1558449028-b53a39d100fc"),
};

export const PRODUCTS = [
  {
    slug: "xavier-1-5kw-3kw-off-grid",
    name: "XAVIER 1.5kW / 3kW Off-Grid Inverter",
    series: "XAVIER",
    category: "single-phase",
    categoryLabel: "Single Phase Off-Grid",
    power: "1.5kW – 3kW",
    efficiency: "93%",
    warranty: "4 Years",
    badge: "Best for Home",
    tagline: "Compact off-grid power with MPPT & WiFi for Bangladeshi homes.",
    description:
      "The Crown Micro XAVIER 1.5kW/3kW off-grid solar inverter supplied by Powerbeam Technologies is ideal for load-shedding backup, rural electrification and small homes in Bangladesh. Pure sine wave, 80-100A MPPT, works with lithium/lead-acid, built-in BMS (3kW) and WiFi monitoring.",
    features: [
      "Pure sine wave, PF 1.0",
      "80A/100A MPPT, PV up to 3000W",
      "12V/24V battery, lithium compatible",
      "Built-in WiFi (3kW) + anti-dust kit",
      "2.5” LCD touch pad",
      "Ideal for fans, lights, TV, fridge",
    ],
    models: [
      {
        model: "XAVIER-1.5KW-PF1",
        power: "1500W",
        pv: "2500W, 30-400VDC",
        battery: "12VDC",
      },
      {
        model: "XAVIER-3KW-PF1",
        power: "3000W",
        pv: "3000W, 60-400VDC",
        battery: "24VDC",
      },
    ],
    specs: [
      { label: "Rated Power", value: "1500VA / 3000VA" },
      { label: "PV Max VOC", value: "400V / 450V" },
      { label: "Charge Current", value: "80A / 100A" },
      { label: "Transfer Time", value: "10ms" },
      { label: "Efficiency", value: "93% peak" },
      { label: "Warranty", value: "4 Years" },
    ],
    image: IMG.home,
    applications: ["Residential", "Off-grid", "Shops"],
  },
  {
    slug: "xavier-iii-4kw-6kw-hybrid",
    name: "XAVIER-III 4kW / 6kW Hybrid Inverter",
    series: "XAVIER-III",
    category: "single-phase",
    categoryLabel: "Single Phase Hybrid",
    power: "4kW – 6kW",
    efficiency: "93%",
    warranty: "4 Years",
    badge: "Hybrid Best Value",
    tagline: "Dual-output hybrid with feed-in to grid & 120A MPPT.",
    description:
      "XAVIER-III hybrid inverters support feed-in to grid, dual output for essential/non-essential loads, 120A MPPT and parallel-ready design. Perfect for Dhaka apartments, offices and commercial backup.",
    features: [
      "Feed-in to grid",
      "Works without battery",
      "Dual output",
      "Built-in WiFi + BMS",
      "5.2” LCD touch",
      "PV 6000W/9000W",
    ],
    models: [
      { model: "XAVIER-III-4KW", power: "4000W", pv: "6000W", battery: "24V" },
      { model: "XAVIER-III-6KW", power: "6000W", pv: "9000W", battery: "48V" },
    ],
    specs: [
      { label: "MPPT Range", value: "60-450VDC" },
      { label: "Max PV", value: "6kW / 9kW" },
      { label: "Solar Charge", value: "120A" },
      { label: "Communication", value: "WiFi/RS485/CAN" },
    ],
    image: IMG.roof,
    applications: ["Home", "Office", "Retail"],
  },
  {
    slug: "arceus-3-6kw-6-5kw-hybrid",
    name: "ARCEUS 3.6kW / 6.5kW Hybrid Inverter",
    series: "ARCEUS",
    category: "single-phase",
    categoryLabel: "Single Phase Hybrid",
    power: "3.6kW – 6.5kW",
    efficiency: "94%",
    warranty: "4 Years",
    badge: "Popular",
    tagline: "High PV input 7800W with parallel up to 9 units.",
    description:
      "ARCEUS series offers 5000W/7800W PV input, 120A MPPT (6.5kW), wide 90-550V range and parallel operation. A top choice for solar hybrid system price in Bangladesh seekers.",
    features: [
      "PV 5000W/7800W",
      "Parallel up to 9 (6.5kW)",
      "Dual output, BMS",
      "WiFi monitoring",
      "Pure sine, PF1",
      "Generator compatible",
    ],
    models: [
      { model: "ARCEUS-3.6KW", power: "3600W", pv: "5000W", battery: "24V" },
      { model: "ARCEUS-6.5KW", power: "6500W", pv: "7800W", battery: "48V" },
    ],
    specs: [
      { label: "MPPT", value: "40-450V / 90-550V" },
      { label: "Peak Efficiency", value: "93.5%/94%" },
      { label: "Display", value: "5.2” LCD" },
    ],
    image: IMG.panel,
    applications: ["Residential", "SME"],
  },
  {
    slug: "elego-star-6-5kw-hybrid",
    name: "ELEGO STAR 6.5kW Hybrid Inverter",
    series: "ELEGO STAR",
    category: "single-phase",
    categoryLabel: "Single Phase Hybrid",
    power: "6.5kW",
    efficiency: "93%",
    warranty: "6 Years",
    badge: "6Y Warranty",
    tagline: "Dual MPPT, touch screen, 16-unit parallel & GEN port.",
    description:
      "Premium single-phase hybrid with dual MPPT 9600W PV, touch screen, separate generator port and 16-unit parallel for villas and commercial buildings.",
    features: [
      "Dual MPPT 9600W",
      "Touch screen + WiFi",
      "GEN port",
      "Parallel 16 units",
      "140A charge",
      "IP21 smart cooling",
    ],
    models: [
      {
        model: "ELEGO-STAR-6.5KW",
        power: "6500W",
        pv: "9600W, 120-400V",
        battery: "48V 38.4-60V",
      },
    ],
    specs: [
      { label: "PV Inputs", value: "2x MPPT" },
      { label: "UPS Switch", value: "<15ms" },
      { label: "Warranty", value: "6 Years" },
    ],
    image: IMG.home,
    applications: ["Villa", "Commercial"],
  },
  {
    slug: "nova-8-6kw-9-8kw-hybrid",
    name: "NOVA 8.6kW / 9.8kW Hybrid Inverter",
    series: "NOVA",
    category: "single-phase",
    categoryLabel: "Single Phase Hybrid",
    power: "8.6kW – 9.8kW",
    efficiency: "93%",
    warranty: "6 Years",
    badge: "High Power",
    tagline: "150A MPPT, 14kW PV for large homes & factories.",
    description:
      "NOVA high-capacity hybrid inverters with 14kW PV array, dual MPPT, 150A charging and 6-unit parallel. Built for large loads and light industrial use.",
    features: [
      "14kW PV input",
      "Dual MPPT, 150A",
      "GEN port + dual output",
      "6-unit parallel",
      "LCD touch + WiFi",
      "48V system",
    ],
    models: [
      { model: "NOVA-8.6KW", power: "8600W", pv: "14000W", battery: "48V" },
      { model: "NOVA-9.8KW", power: "9800W", pv: "14000W", battery: "48V" },
    ],
    specs: [
      { label: "MPPT Range", value: "90-450VDC" },
      { label: "Surge", value: "16kVA/22kVA" },
    ],
    image: IMG.field,
    applications: ["Large Home", "Industrial"],
  },
  {
    slug: "nova-12-6kw-hybrid",
    name: "NOVA 12.6kW Hybrid Inverter Plug & Play",
    series: "NOVA 12.6",
    category: "single-phase",
    categoryLabel: "Single Phase Hybrid",
    power: "12.6kW",
    efficiency: "93.5%",
    warranty: "6 Years",
    badge: "Flagship",
    tagline: "24kW PV, 250A charge, integrated breakers & 16 parallel.",
    description:
      "Flagship 12.6kW with 24kW PV (2 MPPT/4 strings), 250A charging, integrated load+battery breakers and 15kW GEN/AC coupling. Ideal for commercial & mini-grid.",
    features: [
      "24kW PV input",
      "250A charge/discharge",
      "Plug & Play breakers",
      "Parallel 16",
      "Dual AC output",
      "Touch screen",
    ],
    models: [
      {
        model: "NOVA-12.6KW",
        power: "12600W",
        pv: "24000W",
        battery: "48/51.2V",
      },
    ],
    specs: [
      { label: "PV Voltage", value: "100-480V" },
      { label: "GEN Input", value: "Up to 15kW" },
    ],
    image: IMG.ind,
    applications: ["Commercial", "Mini-grid"],
  },
  {
    slug: "elego-oyster-6-5kw-10kw",
    name: "ELEGO OYSTER 6.5kW / 10kW IP66 Hybrid",
    series: "ELEGO OYSTER",
    category: "single-phase",
    categoryLabel: "Single Phase Hybrid IP66",
    power: "6.5kW – 10kW",
    efficiency: "97.3%",
    warranty: "10 Years",
    badge: "IP66 • 10Y",
    tagline: "Outdoor IP66 hybrid with peak shaving & AC coupling.",
    description:
      "Outdoor-ready IP66 hybrid inverters with 210A current, smart scheduling, peak shaving, AC coupling and parallel up to 10. Best for coastal & harsh Bangladesh climates.",
    features: [
      "IP66 outdoor",
      "Peak shaving",
      "210A current",
      "Smart scheduling",
      "GEN intelligent control",
      "10Y warranty",
    ],
    models: [
      {
        model: "ELEGO-OYSTER-6.5KW",
        power: "6500W",
        pv: "9600W",
        battery: "48V",
      },
      {
        model: "ELEGO-OYSTER-10KW",
        power: "10000W",
        pv: "15000W",
        battery: "48V",
      },
    ],
    specs: [
      { label: "Max Efficiency", value: "97.3%" },
      { label: "Parallel", value: "6 / 10 units" },
    ],
    image: IMG.roof,
    applications: ["Residential", "Commercial", "Outdoor"],
  },
  {
    slug: "elego-oyster-5-20kw-three-phase",
    name: "ELEGO OYSTER 5-20kW Three-Phase Hybrid",
    series: "ELEGO OYSTER 3P",
    category: "three-phase-hybrid",
    categoryLabel: "Three Phase Hybrid LV",
    power: "5kW – 20kW",
    efficiency: "97.7%",
    warranty: "5/10 Years",
    badge: "Commercial Pro",
    tagline: "3 MPPT, unbalanced load, independent phase export.",
    description:
      "Low-voltage three-phase hybrid range for offices, apartments and factories. 3 MPPT/6 strings, GEN port, smart load management and 10-unit parallel.",
    features: [
      "5-20kW range",
      "3 MPPT 6 strings",
      "Unbalanced load",
      "Independent export",
      "IP66 + touch",
      "Parallel 10",
    ],
    models: [
      { model: "EOI-OYS-5KW-3P", power: "5kW", pv: "7500W", battery: "40-60V" },
      {
        model: "EOI-OYS-10KW-3P",
        power: "10kW",
        pv: "15000W",
        battery: "40-60V",
      },
      {
        model: "EOI-OYS-20KW-3P",
        power: "20kW",
        pv: "30000W",
        battery: "40-60V",
      },
    ],
    specs: [
      { label: "PV Max", value: "Up to 30kW" },
      { label: "Efficiency", value: "97.7% max" },
    ],
    image: IMG.ind,
    applications: ["Commercial", "Industrial", "Apartments"],
  },
  {
    slug: "elego-oyster-6-30kw-hv",
    name: "ELEGO OYSTER 6-30kW High-Voltage Hybrid",
    series: "ELEGO OYSTER HV",
    category: "three-phase-hybrid",
    categoryLabel: "Three Phase HV Hybrid",
    power: "6kW – 30kW",
    efficiency: "97.4%",
    warranty: "5/10 Years",
    badge: "HV • C&I",
    tagline: "100-800V battery, 45kW PV for C&I scale.",
    description:
      "High-voltage hybrid for C&I with 100-800V battery range, up to 45kW PV, 150% unbalanced load and 10-unit parallel. Pairs with CMLB-5.1HV stacks.",
    features: [
      "HV 100-800V",
      "45kW PV max",
      "150% unbalanced",
      "GEN + smart load",
      "IP66",
      "Parallel 10",
    ],
    models: [
      {
        model: "EOI-OYS-12KW-3PHV",
        power: "12kW",
        pv: "18000W",
        battery: "400V HV",
      },
      {
        model: "EOI-OYS-30KW-3PHV",
        power: "30kW",
        pv: "45000W",
        battery: "400V HV",
      },
    ],
    specs: [
      { label: "Battery", value: "100-800V" },
      { label: "MPPT", value: "2-3 MPPT" },
    ],
    image: IMG.ind,
    applications: ["Factory", "Commercial", "Solar Plant"],
  },
  {
    slug: "volmore-on-grid-single-phase",
    name: "VOLMORE On-Grid Single Phase 1kW-10kW",
    series: "VOLMORE SP",
    category: "on-grid",
    categoryLabel: "On-Grid Single Phase",
    power: "1kW – 10kW",
    efficiency: "98.3%",
    warranty: "10 Years",
    badge: "Net-Metering",
    tagline: "97.6-98.3% efficiency for DPDC/DESCO net-metering.",
    description:
      "Single-phase on-grid inverters with dual MPPT, IP66, WiFi/4G and reactive power control. Perfect for residential net-metering in Bangladesh.",
    features: [
      "1-10kW range",
      "Up to 98.3%",
      "IP66 + LCD touch",
      "WiFi/4G optional",
      "Type II/III SPD",
      "10Y warranty",
    ],
    models: [
      { model: "VMGI-3KW-SP", power: "3kW", pv: "600V max", battery: "—" },
      { model: "VMGI-5KW-SP", power: "5kW", pv: "600V max", battery: "—" },
      {
        model: "VMGI-10KW-SP",
        power: "10kW",
        pv: "600V, 3 MPPT",
        battery: "—",
      },
    ],
    specs: [
      { label: "MPPT", value: "1-3 MPPT" },
      { label: "Grid", value: "230V 50/60Hz" },
    ],
    image: IMG.roof,
    applications: ["Home Net-meter", "Shop", "Office"],
  },
  {
    slug: "volmore-on-grid-three-phase",
    name: "VOLMORE On-Grid Three Phase 3kW-125kW",
    series: "VOLMORE 3P",
    category: "on-grid",
    categoryLabel: "On-Grid Three Phase",
    power: "3kW – 125kW",
    efficiency: "98.7%",
    warranty: "10 Years",
    badge: "Industrial",
    tagline: "1100V PV, up to 98.7% for factories & rooftops.",
    description:
      "Three-phase on-grid portfolio 3kW to 125kW with 1100V PV, multi-MPPT, IP66 and smart monitoring. Ideal for industrial rooftops, schools, hospitals.",
    features: [
      "3-125kW",
      "1100V PV",
      "Up to 98.7%",
      "2-8 MPPT",
      "IP66",
      "10Y warranty",
    ],
    models: [
      { model: "VMGI-10KW", power: "10kW", pv: "1100V", battery: "—" },
      { model: "VMGI-50KW", power: "50kW", pv: "1100V, 4 MPPT", battery: "—" },
      {
        model: "VMGI-125KW",
        power: "125kW",
        pv: "1100V, 8 MPPT",
        battery: "—",
      },
    ],
    specs: [
      { label: "Voltage", value: "400V 3P+N" },
      { label: "Monitoring", value: "RS485/WiFi/4G" },
    ],
    image: IMG.field,
    applications: ["Factory", "Hospital", "University"],
  },
  {
    slug: "volmore-350kw-utility",
    name: "VOLMORE 350kW Utility On-Grid Inverter",
    series: "VOLMORE 350",
    category: "on-grid",
    categoryLabel: "Utility Scale",
    power: "350kW",
    efficiency: "99%",
    warranty: "10 Years",
    badge: "Utility",
    tagline: "1500V, 99% efficiency with smart I-V curve.",
    description:
      "Utility-scale 350kW string inverter with 1500V DC, 12-16 MPPT, smart I-V diagnostics and IP66 for solar parks and large C&I in Bangladesh.",
    features: [
      "350kW, 1500V",
      "99% max eff",
      "12/16 MPPT",
      "Smart I-V curve",
      "IP66",
      "PLC+RS485",
    ],
    models: [
      {
        model: "VMGI-350KW-1",
        power: "350kW",
        pv: "1500V, 32 strings",
        battery: "—",
      },
    ],
    specs: [
      { label: "AC", value: "800V 3W+PE" },
      { label: "MPPT", value: "16/12" },
    ],
    image: IMG.field,
    applications: ["Solar Park", "Utility", "Mega Factory"],
  },
  {
    slug: "solar-pump-controllers",
    name: "Solar Pump Controllers CM-SPC 2.2kW-200kW",
    series: "CM-SPC",
    category: "solar-pump",
    categoryLabel: "Solar Pump",
    power: "2.2kW – 200kW",
    efficiency: "99.8% MPPT",
    warranty: "18 Months",
    badge: "Agri Solar",
    tagline: "Solar irrigation with hybrid AC/DC & dry-run protection.",
    description:
      "Solar water pump controllers for 3HP to 270HP motors. Auto-switch solar/grid, weak-light operation, Web/App monitoring and multi-pump protection for BADC/BMDA projects.",
    features: [
      "2.2-200kW",
      "99.8% MPPT",
      "Hybrid AC/DC",
      "Dry-run protect",
      "App monitoring",
      "Zero programming",
    ],
    models: [
      { model: "CM-SPC50-11KW", power: "11kW", pv: "220-900VDC", battery: "—" },
      {
        model: "CM-SPC33-55KW",
        power: "55kW",
        pv: "500-750V MPPT",
        battery: "—",
      },
      {
        model: "CM-SPC33-160KW",
        power: "160kW",
        pv: "500-750V MPPT",
        battery: "—",
      },
    ],
    specs: [
      { label: "Output", value: "0-380/480V 3P" },
      { label: "Control", value: "V/F, SVC" },
    ],
    image: IMG.agri,
    applications: ["Irrigation", "Deep Tube-well", "Agro"],
  },
  {
    slug: "nura-6-5kw-all-in-one-ess",
    name: "NURA 6.5kW / 5kWh All-in-One ESS",
    series: "NURA",
    category: "ess",
    categoryLabel: "All-in-One ESS",
    power: "6.5kW / 5-15kWh",
    efficiency: "93%",
    warranty: "10 Years",
    badge: "All-in-One",
    tagline: "Inverter + LiFePO4 in one cabinet, 15-min install.",
    description:
      "All-in-one energy storage: 6.5kW hybrid inverter + 5.12kWh LiFePO4 expandable to 15kWh. <10ms switch, dual MPPT 9600W, parallel 16. Best home ESS in Bangladesh.",
    features: [
      "6.5kW+5kWh",
      "Expandable 15kWh",
      "<10ms switch",
      "Dual MPPT 9600W",
      "Parallel 16",
      "Touch + WiFi",
    ],
    models: [
      {
        model: "NURA6.5kW",
        power: "6500W",
        pv: "9600W",
        battery: "51.2V 100Ah",
      },
    ],
    specs: [
      { label: "Battery", value: "5.12kWh Li-ion" },
      { label: "Install", value: "<15 min" },
    ],
    image: IMG.battery,
    applications: ["Premium Home", "Villa", "Office"],
  },
  {
    slug: "lifepo4-residential-battery",
    name: "Residential LiFePO4 Batteries 1.28-14.3kWh",
    series: "CMLB",
    category: "ess",
    categoryLabel: "LiFePO4 Battery",
    power: "12.8V-51.2V",
    efficiency: "8000+ Cycles",
    warranty: "5 Years",
    badge: "Grade A",
    tagline: "Transparent, Wall & Mobile with smart BMS & WiFi.",
    description:
      "Grade A LiFePO4 batteries: transparent 12.8V/25.6V, wall-mounted 51.2V 100Ah (5.12kWh) and mobile 11.7/14.3kWh. 8000+ cycles, CAN/RS485, WiFi/Bluetooth, 16-parallel.",
    features: [
      "Grade A cells",
      "8000+ cycles",
      "Smart BMS",
      "WiFi/BT monitor",
      "16-parallel",
      "IP65",
    ],
    models: [
      {
        model: "CMLB-12.8V-200",
        power: "2.56kWh",
        pv: "—",
        battery: "12.8V 200Ah",
      },
      {
        model: "CMLB-51.2-100-WM",
        power: "5.12kWh",
        pv: "—",
        battery: "51.2V 100Ah",
      },
      {
        model: "CMLB-51.2-280",
        power: "14.33kWh",
        pv: "—",
        battery: "51.2V 280Ah",
      },
    ],
    specs: [
      { label: "Cycle Life", value: ">8000 @50% DOD" },
      { label: "Design Life", value: "15 Years" },
    ],
    image: IMG.battery,
    applications: ["Home Backup", "Off-grid", "Hybrid"],
  },
  {
    slug: "high-voltage-battery-ess",
    name: "High-Voltage Battery CMLB-5.1HV Stack to 900kWh",
    series: "CMLB-HV",
    category: "ess",
    categoryLabel: "C&I HV ESS",
    power: "5.09kWh/module",
    efficiency: "95% DOD",
    warranty: "10 Years",
    badge: "C&I ESS",
    tagline: "45kWh/stack, 900kWh system for factories.",
    description:
      "Stackable high-voltage LFP: 5.09kWh modules, 2-9 series/stack (45kWh), up to 20 stacks parallel (900kWh). IP65, remote upgrade, pairs with 6-30kW HV hybrid.",
    features: [
      "5.09kWh module",
      "45kWh/stack",
      "900kWh max",
      "95% DOD",
      "IP65",
      "Remote OTA",
    ],
    models: [
      {
        model: "CMLB-5.1HV",
        power: "5.069kWh",
        pv: "—",
        battery: "70.4V 72Ah",
      },
    ],
    specs: [
      { label: "Voltage Range", value: "61.6-80.3V/mod" },
      { label: "Cycles", value: "6000 cycles" },
    ],
    image: IMG.ind,
    applications: ["Factory", "Microgrid", "Commercial"],
  },
];
export const getProduct = (slug) => PRODUCTS.find((p) => p.slug === slug);
export const getRelated = (slug, cat) =>
  PRODUCTS.filter((p) => p.slug !== slug && p.category === cat).slice(0, 3);
